version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: headset
      MYSQL_PASSWORD: eFAl5a0JPE
      MYSQL_DATABASE: headset
      MYSQL_ROOT_PASSWORD: w4ysER82ka
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend
networks:
  frontend:
  backend:
